# Generated by Django 4.0 on 2021-12-11 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('age', models.CharField(choices=[('18-25', 'From 18 25'), ('26-33', 'From 26 33'), ('34-40', 'From 34 40'), ('40+', 'More 40')], max_length=5, verbose_name='age')),
                ('favorite_social_network', models.CharField(choices=[('facebook', 'Facebook'), ('whatsapp', 'Whatsapp'), ('twitter', 'Twitter'), ('instagram', 'Instagram'), ('tiktok', 'Tiktok')], max_length=9)),
                ('time_facebook_avg', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='time facebook avg')),
                ('time_whatsapp_avg', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='time whatsapp avg')),
                ('time_twitter_avg', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='time twitter avg')),
                ('time_instagram_avg', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='time instagram avg')),
                ('time_tiktok_avg', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='time tiktok avg')),
            ],
        ),
    ]
